name: hello
on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: 1번 단계
        run: echo "여기는 실행됨"

      - name: 2번 단계 - 고의 실패
        run: exit 1                # 0이 아닌 종료 코드 = 실패

      - name: 3번 단계
        run: echo "여기는 실행되지 않음"